version: '3.3'

services:
  php-fpm:
    container_name: quickfs-fpm
    build:
      context: ./docker/php-fpm
    args:
      - XDEBUG_ON=1
    restart: unless-stopped
    volumes:
      - .:/var/www/html
  php-cli:
    container_name: quickfs-cli
    build:
      context: ./docker/php-cli
    volumes:
      - .:/var/www/html
  nginx:
    container_name: quickfs-nginx
    image: nginx:alpine
    build:
      context: ./docker/nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - .:/var/www/html
  redis:
    container_name: quickfs-redis
    image: redis:alpine
    restart: unless-stopped
    depends_on:
      - php-fpm
    volumes:
      - /redis/data
